name: Supernova Analyze

on:
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CLI
        run: npm install -g @supernovaio/cli

      - name: Login to Supernova
        env:
          SUPERNOVA_API_KEY: ${{ secrets.SUPERNOVA_API_KEY }}
        run: |
          supernova login --apiKey "$SUPERNOVA_API_KEY"

      - name: Run analysis
        env:
          SUPERNOVA_DESIGN_SYSTEM_ID: ${{ secrets.SUPERNOVA_DESIGN_SYSTEM_ID }}
        run: |
          supernova code analyze \
            -d "$SUPERNOVA_DESIGN_SYSTEM_ID"
